/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "DIN2.h"
#include "DIN2_aliases.h"
#include "DOUT1.h"
#include "DOUT1_aliases.h"
#include "RELAY3.h"
#include "RELAY3_aliases.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "ACC_ISR.h"
#include "RELAY2.h"
#include "RELAY2_aliases.h"
#include "DIN1.h"
#include "DIN1_aliases.h"
#include "DOUT2.h"
#include "DOUT2_aliases.h"
#include "DOUT3.h"
#include "DOUT3_aliases.h"
#include "DOUT4.h"
#include "DOUT4_aliases.h"
#include "Bootloadable.h"
#include "RELAY1.h"
#include "RELAY1_aliases.h"
#include "DIN3.h"
#include "DIN3_aliases.h"
#include "DIN4.h"
#include "DIN4_aliases.h"
#include "DIN5.h"
#include "DIN5_aliases.h"
#include "DIN6.h"
#include "DIN6_aliases.h"
#include "DIN7.h"
#include "DIN7_aliases.h"
#include "DIN8.h"
#include "DIN8_aliases.h"
#include "ACC.h"
#include "ACC_aliases.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "UART_SCBCLK.h"
#include "UART_rx_wake.h"
#include "UART_rx_wake_aliases.h"
#include "UART_RX_WAKEUP_IRQ.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

